### ISSUE TITLE
Integration tests fail intermittenly due to hystrix plugin registration

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-rest#103]
```
FAILURE! testFirstIntegrationTest(com.redhat.lightblue.rest.crud.ITCaseCrudResourceTest)
...
Caused by: java.lang.IllegalStateException: Another strategy was already registered. 
at com.netflix.hystrix.strategy.HystrixPlugins.registerMetricsPublisher(HystrixPlugins.java:168) 
at com.redhat.lightblue.util.ServoGraphiteSetup.doInitialize(ServoGraphiteSetup.java:185) 
at com.redhat.lightblue.util.ServoGraphiteSetup.initialize(ServoGraphiteSetup.java:74) 
at com.redhat.lightblue.rest.crud.CrudResource.<clinit>(CrudResource.java:31)
```

It's failing pretty often on travis for openjdk7 builds, less (if at all) for oraclejdk8.  I can't reproduce it locally.  Maybe travis has an alias for `mvn`?  I tried with the exact same args and it builds fine every time.

**Comment by jewzaam** [comment]
@luan-cestari giving this to you as it's slowing down getting fixes pushed to rest repo.

**Comment by luan-cestari** [comment]
@jewzaam OK, I will investigate this issue

**Comment by luan-cestari** [comment]
Note: maybe we could use ```type``` to see if any command has an alias and ```which``` to see if it is using alternatives

**Comment by luan-cestari** [comment]
Some work made on https://github.com/lightblue-platform/lightblue-rest/pull/99 and on the core that might solve this issue (reseting  the previous strategy) . Let's wait a month to see if this issue happens again in any rest build (as it have integration tests

**Comment by luan-cestari** [comment]
Note:I built the PR that have the fix a couple of times an this issue haven't occurred so far

**Comment by luan-cestari** [comment]
The rest PR related to solve this issue was build several times after the last update I made and It didn't have the problem mentioned by this issue

**Comment by jewzaam** [comment]
@luan-cestari if it's not happening should we close it?

**Comment by luan-cestari** [comment]
@jewzaam I agree with you. Closing this issue
