### ISSUE TITLE
Create a reusable and easily consumable test harness for client code that need to test against a mocked lightblue instance

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-rest#105]
There is no clear way to do this. It looks like some work has already been doing using Arquillian. This issue is about packaging this in a reusable way.

**Comment by jewzaam** [comment]
Duplicate of https://github.com/lightblue-platform/lightblue-core/issues/52 (which should live in rest not core I guess)

**Comment by dcrissman** [comment]
Closing as duplicate
