### ISSUE TITLE
Fix Hystrix configuration

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-rest#115]
Found strange behavior case when the commands were taking more than one second to respond and after looking into the Hystrix documentation (which  was outdated https://github.com/Netflix/Hystrix/issues/714 ) and code I understood that Hystrix changed its default behavior. After search more a bit found the https://github.com/Netflix/Hystrix/blob/master/CHANGELOG.md that make it clear that now even semaphore isolation strategy will timeout. I opened an issue https://github.com/Netflix/Hystrix/issues/714 asking if they could update the documentation and even change that property name and they are working on it. On meanwhile, we need to make sure that every project that relys on Hystrix have its configuration file with https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutInMilliseconds property with the reasonable amount of time that you would expect that after that threshold it should fire a time out exception from Hystrix. (Note: so this also apply for our puppet scripts that may need to specify the  timeout  parameter as well)  .

**Comment by jewzaam** [comment]
Nice find, I added issues to ldap and mongo, as they use this isolation strategy for tests as well.

**Comment by luan-cestari** [comment]
Thanks. O think they will also rename that property, so It would be ncie that we leave at least one issue one about this to make sure that we have the right property set (as we can get a newer version during lightblue release and have a simialr problem once again)

**Comment by luan-cestari** [comment]
The issue in Hystrix about the renaming -> https://github.com/Netflix/Hystrix/issues/673
