### ISSUE TITLE
LDAP Authorization cache doesn't appear to be working

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-rest#116]
The changes implemented in https://github.com/lightblue-platform/lightblue-rest/pull/99 were recently deployed to our dev environment, and we lost all ability to access any of the REST endpoints (403 returned from JBoss in all cases).  Upon investigation, no information was being written to the access.log file, so it seemed like LDAP wasn't even being consulted for user roles.  I reverted the login module code to the version prior to the above referenced PR, and was able to access the services again.  So it appears that something related to authorization cache is not working correctly.  I didn't debug in detail, as I was primarily focused on restoring service in dev, so @luan-cestari, can you take a look at this when you have a chance?  Perhaps we can replicate the behavior in a unit test using an LDAP instance in order to get it resolved.

**Comment by luan-cestari** [comment]
@derek63 What about I make a PR with more log statements so we  could have a better picture of the problem and i parallel I will also work creating integration tests to this module (which will take more time to finish)?

**Comment by derek63** [comment]
Sure, more logging statements could help to isolate where the issue lies, and we can use that to troubleshoot.  Let me know when you get that created and I can merge it in.

**Comment by luan-cestari** [comment]
Created the PR for the log. Feel free to review it  & merge it -> https://github.com/lightblue-platform/lightblue-rest/pull/117/files

**Comment by luan-cestari** [comment]
New PR for this problem -> https://github.com/lightblue-platform/lightblue-rest/pull/119
