### ISSUE TITLE
data and metadata services display incorrect errorCode when datastore timeout occurs

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-rest#12]
Right now when the services timeout when trying to connect to the backend datastore, they return the following error messages

{
    "objectType": "error",
    "context": "GetEntityNamesCommand/getEntityNames",
    "errorCode": "metadata:IllFormedMetadata",
    "msg": "Timed out while waiting to connect after 10000 ms"
}

{
    "status": "ERROR",
    "modifiedCount": 0,
    "matchCount": 0,
    "errors": [
        {
            "objectType": "error",
            "context": "rest/FindCommand/user/find(user:1.0.0)/getEntityMetadata(user:1.0.0)/getEntityInfo(user)",
            "errorCode": "metadata:IllFormedMetadata",
            "msg": "Timed out while waiting to connect after 10000 ms"
        }
    ]

}

The msg returned correctly represents what is happening in both services, however the errorCode does not.  We should probably create a new errorCode that represents a problem connecting to the datastore.

**Comment by luan-cestari** [comment]
PRs for this issue -> https://github.com/lightblue-platform/lightblue-core/pull/344  ,  https://github.com/lightblue-platform/lightblue-mongo/pull/84

**Comment by jewzaam** [comment]
@luan-cestari can this be closed?

**Comment by luan-cestari** [comment]
@jewzaam I think it can be closed, I thought @derek63 would test to validate the set of PR that were merged before we close this issue
