### ISSUE TITLE
data and metadata services display incorrect errorCode when failing to authenticate against the datastore

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-rest#13]
Right now when the services can't connect to mongo because the credentials don't exist, they return the following error messages

{
    "objectType": "error",
    "context": "GetEntityNamesCommand/getEntityNames",
    "errorCode": "metadata:IllFormedMetadata",
    "msg": "{ \"serverUsed\" : \"supersecretmongonode.nottherealhost.com:27017\" , \"ok\" : 0.0 , \"errmsg\" : \"auth failed\" , \"code\" : 18}"
}

{
    "status": "ERROR",
    "modifiedCount": 0,
    "matchCount": 0,
    "errors": [
        {
            "objectType": "error",
            "context": "rest/FindCommand/user/find(user:1.0.0)/getEntityMetadata(user:1.0.0)/getEntityInfo(user)",
            "errorCode": "metadata:IllFormedMetadata",
            "msg": "{ \"serverUsed\" : \"supersecretmongonode.nottherealhost.com:27017\" , \"ok\" : 0.0 , \"errmsg\" : \"auth failed\" , \"code\" : 18}"
        }
    ]
}

The msg returned correctly represents what is happening in both services, however the errorCode does not. We should probably create a new errorCode that represents a problem with authenticating against the datastore.

**Comment by luan-cestari** [comment]
The PRs https://github.com/lightblue-platform/lightblue-core/pull/339 and https://github.com/lightblue-platform/lightblue-mongo/pull/81 might solve this issue

**Comment by luan-cestari** [comment]
Could someone try to reproduce the issue to see if the error code will change please? I think the data service might need to get the metadata service before hand so this might solve the issue (or I will have to investigate another point to fix)

**Comment by derek63** [comment]
The way to reproduce this issue would be to remove the Mongo credentials used by the service from the data store it is connecting to.  Let's not do this in our dev environment, but someone could definitely do it locally on their workstation.

**Comment by luan-cestari** [comment]
new PRs to this issue -> https://github.com/lightblue-platform/lightblue-core/pull/344  ,  https://github.com/lightblue-platform/lightblue-mongo/pull/84

**Comment by jewzaam** [comment]
@luan-cestari can this be closed?

**Comment by luan-cestari** [comment]
@jewzaam yeah, we can close. The PRs related to this issue were both merged. I thought @derek63 would reproduce the problem to see if he agree the changes made satisfy the requirements.
