### ISSUE TITLE
Dynamically configure maven dependencies for lightblue plugins

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-rest#162]
From a maven dependency perspective, all possible plugins must be listed in lightblue-rest's pom file. You can already fine tune which plugins are actually used at runtime via the lightblue-metadata.json configuration, but all the possible plugins must still be listed in the pom.

It would be idea if you could truly configure what plugins you wanted to use. This would be beneficial for highly customized plugins that not anyone would want to use, or if you just want a lighter weight installation.

**Comment by dcrissman** [comment]
Found this article: http://stackoverflow.com/questions/402330/is-it-possible-to-add-to-classpath-dynamically-in-java

Maybe we create a 'magic' directory and any jars in it get loaded at runtime?

**Comment by jewzaam** [comment]
Probably could put the jar's for the hooks and controllers into a module, keeping the lightblue-rest pom clean.  There are unit tests that depend on some of those things.  Maybe they can be put into a separate module that has those hook and controller dependencies with a scope of test.  The mongo controller is used all over the place, though, so we may want to deal with pulling that out separately.  Could we start with just hooks to keep the scope smaller?

**Comment by alechenninger** [comment]
I do this commonly with combination of URLClassLoader and ServiceLoader: https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html

**Comment by dcrissman** [comment]
@alechenninger Does that get the jars onto the classpath?

I see once on the classpath, it is easily able to load services. Lightblue currently uses reflection to instantiate hooks and other plugins. I am not sure of the merits of one approach over the other.

I found an <a href=https://docs.oracle.com/javase/tutorial/ext/basics/spi.html#run-the-client">example</a>, of ServiceLoader, where they are setting the java.ext.dirs flag on java. Which kind of goes back to the magic directory solution.

**Comment by alechenninger** [comment]
You can use `URLClassLoader` to create a classpath from a jar or directory. So, if you land the hooks somewhere and add configuration to know where to look for hook jars, you can create these classloaders and load the services in them at runtime. Or, as naveen said, you could use some kind of "hooks" module that users could populate using puppet, and then you could use `ServiceLoader` to discover the hooks if you wanted.

**Comment by dcrissman** [comment]
I have added some PRs, but this all still needs testing and is not yet ready to be merged. I marked everything as in progress. That said, feel free to start reviewing.

**Comment by dcrissman** [comment]
I have made progress to the point that I can manually drop jar files into some directory and tell lightblue how to pull the in and add them to the class path. I am using lightblue-ldap as a test case.

My current thinking is that I will add the ability for lightblue-ldap to generate an rpm that can deploy the individual jars. This includes lightblue-ldap-core/crud/metadata/common and a ldap library (that does not have an rpm itself that I can find). 

The question now, is where do we want the jar files to live? I would like to keep it non-specific to jboss if possible. My current thinking is a /var/lib/lightblue/ directory, but wanted to get some feedback before proceeding. Thoughts?

**Comment by alechenninger** [comment]
> The question now, is where do we want the jar files to live?
Why not configurable in a properties file in the properties module? You can also have a default of course

**Comment by dcrissman** [comment]
To clarify, I will be using maven to generate the rpm similar to other lightblue deployable artefacts. So the install directory will be configurable, but the question is what to set the rpm.install.basedir too (or default if you prefer)?

As far as how to tell lightblue where the jar files are, will be configurable. See #162 for how that will work.

**Comment by dcrissman** [comment]
Going to drop the jars in /usr/share/java/lightblue/lightblue-rest

**Comment by kahowell** [comment]
FYI, we want to automate deployment of esbtools/lightblue-notification-hook. Waiting on this work to be complete before proceeding.

**Comment by dcrissman** [comment]
Keeping this issue alive because work still needs to be done.
