### ISSUE TITLE
Update login module (auth) to cache authz

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-rest#17]
- [ ] Update to cache a small set of authorizations from LDAP
- [ ] Update hystrix command to use cache if request to LDAP fails
- [ ] Update login module to use cache in some cases (assumes we want to not hit LDAP for every single request but can trust cached data for a period of time)

**Comment by jewzaam** [comment]
We might have made this no longer a command while debugging graphite issues.

**Comment by derek63** [comment]
We did remove the command in https://github.com/lightblue-platform/lightblue-rest/pull/72.  Guess it can be added back now we have the statsd thing happening

**Comment by jewzaam** [comment]
Let's add it back in then so we can use the fallback feature from hystrix commands as well as collect metrics for the command in general.

**Comment by luan-cestari** [comment]
Made the changes requested. I saw that it already had a basic idea of where one of the caches would be , and also reviewing the history of the changes there (like #72 ), it required another cache (so it is one for the hystrix command and another for the list returned). I think we could refactor the hystrix command return the List<String> (so it would avoid an special case where the query returns fine but then when it process the returned value it get an exception, which I think it should be Hystrix Command role to deal with that). One thing that I couldn't find is the set of test to fix and to enhance after this change. Do I have to create all the tests as there were no test ?

The code returned also create a new Hysttrix command in case of the LDAP service failure so we could track a little bit better the usage of the fallback.

Also put some notes asking suggestions about default values and where to load the appropriate values . 

Let me know suggestion and fixes.
