### ISSUE TITLE
Query timeout doesn't return a response

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-rest#178]
I'm testing what happens when attempting to pull a large set of data out of lightblue.  If the rest layer times out I get an empty response.  I see in server logs that the rest hystrix command timed out and threw UnhandledException:

```
2015-10-05 12:09:59,269 [https_executor-threads - 399] ERROR 
[org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/rest/data].
[com.redhat.lightblue.rest.crud.RestApplication]] JBWEB000236: Servlet.service() for servlet 
com.redhat.lightblue.rest.crud.RestApplication threw exception: 
org.jboss.resteasy.spi.UnhandledException: com.netflix.hystrix.exception.HystrixRuntimeException: 
FindCommand timed-out and no fallback available.
```

Then server log spews the full stack for the timeout, but using curl I get this:

```
$ curl "https://<host>/rest/data/find/<entity>/<version>"
curl: (52) Empty reply from server
```

Note the hystrix command times out at 10 seconds, so I have curl stop at 15 so I don't have to keep

**Comment by Abhikos** [comment]
@jewzaam: Just wanted to understand it more, according to this flow [https://raw.githubusercontent.com/wiki/Netflix/Hystrix/images/hystrix-command-flow-chart.png](url). 
Is implementing fallback to provide a generic response would help here?

**Comment by jewzaam** [comment]
We have since stopped using hystrix in this project.

**Comment by Abhikos** [comment]
@jewzaam: what were the reasons for removing hystrix from this project?

**Comment by jewzaam** [comment]
We were working around the limits hystrix setup and not leveraging fallbacks.  Basically, we found it on application to result in restrictions we didn't want and provided no benefits that were being leveraged.  The last thing we kept it around for was metrics extracted to graphite, but found those to be not useful too.

**Comment by Abhikos** [comment]
@jewzaam thanks for the explanation, Is there any plans to remove metrics as well?

**Comment by jewzaam** [comment]
With removing hystrix we no longer have the metrics provided by hystrix being sent to graphite.  We have other metrics published via collectd/statsd on the host systems.  At this time we don't have any application specific metrics being collected that I'm aware of.
