### ISSUE TITLE
Default entity version doesn't work with find()

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-rest#185]
MigrationJob:2.0.1 is a default version, but:

curl $host/rest/data/find/migrationJob?Q=configurationName:userNameChangeValidation"
{"status":"ERROR","modifiedCount":0,"matchCount":0,"hostname":"lightbluecrud1.dev.a1.vary.redhat.com","errors":[{"objectType":"error","context":"rest/FindCommand/migrationJob/find(migrationJob:null)/getEntityMetadata(migrationJob:null)","errorCode":"mongo-metadata:UnknownVersion","msg":"migrationJob:null"}]}
{
    "errors": [
        {
            "context": "rest/FindCommand/migrationJob/find(migrationJob:null)/getEntityMetadata(migrationJob:null)",
            "errorCode": "mongo-metadata:UnknownVersion",
            "msg": "migrationJob:null",
            "objectType": "error"
        }
    ],
    "hostname": "lightbluecrud1.dev.a1.vary.redhat.com",
    "matchCount": 0,
    "modifiedCount": 0,
    "status": "ERROR"
}

**Comment by jewzaam** [comment]
Note this works if you use the full query language so I assume it's a problem with the simple query language requiring a version.

```
curl -H Content-Type:application/json -X POST "https://$host/rest/data/find/migrationJob/" -d '{
    "objectType": "migrationJob",
    "query": {
        "field": "configurationName",
        "op": "$eq",
        "rvalue": "userNameChangeValidation"
    },
    "projection": {
        "field": "*",
        "include": true
    }
}'
```

**Comment by bserdar** [comment]
The problem is in core: FindRequest.fromJson(findRequest.toString()) sets version to "null", not to null.
