### ISSUE TITLE
Include a session UUID in MDC

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-rest#249]
This would allow us to group all logs that occurred within a session together. The logger pattern would also need to expose this.

**Comment by dcrissman** [comment]
An example done elsewhere
https://github.com/candlepin/candlepin/blob/master/common/src/main/java/org/candlepin/common/filter/LoggingFilter.java

**Comment by paterczm** [comment]
You can add thread name to access logs to be able to align them with sever.log entries. Not the same thing as you propose here, but serves the same purpose - makes aligning logged events easier.

http://tomcat.apache.org/tomcat-7.0-doc/config/valve.html#Access_Log_Valve/Attributes
> %I - Current request thread name (can compare later with stacktraces)
