### ISSUE TITLE
Is it possible to configure datasources.json with mongodb credentials?

### ISSUE THREAD

**Issue by JankiGadhiya** [lightblue-platform/lightblue-rest#254]
If the answer is yes then how can i do that?

can any one please suggest the changes i need to make in `datasources.json`

**Comment by bserdar** [comment]
You can check the documents here:

https://github.com/lightblue-platform/lightblue-docs-developer/tree/master/configuration

**Comment by JankiGadhiya** [comment]
After adding that configs i am not able to start my wildfly. getting this error :

```
16:51:02,777 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "lightblue-rest-crud-2.10.0-SNAPSHOT.war")]) - failure description: "WFLYSRV0137: No deployment content with hash 10f8acfd72e76558206d5ff8c77459c6dbd47abf is available in the deployment content repository for deployment 'lightblue-rest-crud-2.10.0-SNAPSHOT.war'. This is a fatal boot error. To correct the problem, either restart with the --admin-only switch set and use the CLI to install the missing content or remove it from the configuration, or remove the deployment from the xml configuration file and restart."
16:51:02,796 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
```

**Comment by bserdar** [comment]
This is a wildfly boot error, it looks like it can't deploy the war file.
Maybe you have more than one war deployed, or the contents of the war are
corrupt? It doesn't look like it is related to configuration. It is also
possible that there is another error before this that might tell you what
the actual error is.

**Comment by JankiGadhiya** [comment]
Thank you @bserdar 

There is not error other than this.

Can you please tell me how to remove that deployments ? As i am not able to start admin console and `standalone/deployments/` folder is also empty.

**Comment by bserdar** [comment]
you don't need the admin console. Put the war file under the deployments
directory, and they should be deployed.

**Comment by JankiGadhiya** [comment]
From this mechanism options which mechanism you suggest me to use :

GSSAPI_MECHANISM, MONGODB_CR_MECHANISM, MONGODB_X509_MECHANISM, PLAIN_MECHANSM

and now i am getting some ssl related error :(

**Comment by bserdar** [comment]
Please understand that we can't help you every step along the way. There
are ways you can turn off ssl settings, and these are documented, so please
read the documents. This is not a technical help forum, but an issue
reporting system.
