### ISSUE TITLE
Light blue support for SCRAM-SHA-1 authentication mechanism of MongoDB

### ISSUE THREAD

**Issue by JankiGadhiya** [lightblue-platform/lightblue-rest#255]
As the latest version of mongodb is 3.2.10 and from version 3.x the mongodb has default SCRAM-SHA-1 authentication mechanism.

and light-blue is supporting only GSSAPI_MECHANISM, MONGODB_CR_MECHANISM, MONGODB_X509_MECHANISM, PLAIN_MECHANSM.

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-mongo/issues/325
