### ISSUE TITLE
Use UnboundID for LDAP communication in login module

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-rest#257]
Built-in Java LDAP support is a joke, and requires us to write ugly code like this:
```
private Hashtable<String, Object> env = new Hashtable<>();
...
env.put(Context.SECURITY_AUTHENTICATION, "simple");
env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.ldap.LdapCtxFactory");
env.put(Context.PROVIDER_URL, server);
...
System.setProperty("javax.net.ssl.trustStore", trustStore);
System.setProperty("javax.net.ssl.trustStorePassword", trustStorePassword);
```
Let's use a sane LDAP library that doesn't require System.setProperty calls and Hashtables.

I assumed UnboundID since (I think) that is what was used that in the lightblue-ldap project, but I am open to others as well (spring-ldap, etc.)

**Comment by dcrissman** [comment]
FWIW UnboundID is what lightblue-ldap uses.
