### ISSUE TITLE
Allow login module to accept requests "acting as" another user than requester

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-rest#28]
For the data management application, it is desirable that users be able to construct an arbitrary JSON request to query Lightblue. However, this requires the application to essentially recreate Lightblue's authorization logic in order to prevent user's from writing queries they aren't allowed to perform. The alternative is adding support to the login module in Lightblue for requests to be performed as a different user than the one actually sending the request.

Of course the ability to do this might require that the requester can assert that the are allowed to operate as that user (either by proving that user is logged into that application or by being a part of a separate role that has the ability to impersonate other users).

**Comment by alechenninger** [comment]
Need to resolve this soon. To be clear, the use case is a applications that are front ends for the services. Users can construct any arbitrary query (even raw json) and send it up to the application. If the _application_ took care of authorization, the application would have to recreate all of lightblue's permission logic: get roles for the user, understand the capabilities of those roles, examine the metadata of entities they are interacting with... all of the things that lightblue already does. It would be simpler to just forward the request to lightblue, but tell lightblue hey, I know _I'm_ sending you this request, but this is on behalf of this _other_ user... can this user do this?

We can't call the lightblue service as if we were the user, because in order to do that we must authenticate with a certificate. That would require the user uploading their certificate to the application in order to login, and then setting up a new httpclient server side that used the right cert for the current user's session to forward requests to lightblue.

The proposed solution is:
- Add a role that is allowed to submit requests that should be authorized via a different user's roles
- In that case, examine some header in the request that should say what user to user (this can be done in login module: https://developer.jboss.org/wiki/WebAuthenticationUsingHTTPRequestParameters)
- If this header is not provided, use the role of the requester as normal

Alternatively, the client-side javascript could make the call to lightblue directly, and pass along some credentials that it has obtained from a trusted source. I think this is a preferred solution for a number of reasons, but I'm not entirely sure this works how I think it would work. This would require Lightblue to accept cross origin requests (see [cross origin resource sharing](http://www.html5rocks.com/en/tutorials/cors/)) and some other authentication scheme, like SAML or OAuth. But this is unfamiliar territory for me. I guess the AJAX requests would include a SAML token in header or cookie.

**Comment by jewzaam** [comment]
CORS is fine, but the problem with "some other authentication scheme" is there's a bug with the version of JBoss EAP we can use.  I'm trying to find the reference to that, got it somewhere....

**Comment by bserdar** [comment]
How about something like this:
  - Add a flag to caller's cert, saying the caller can mimic others
  - If that flag is set, login module would accept another user, and
retrieve roles for that user, not the caller

**Comment by bserdar** [comment]
Ignore that. A separate role that allows mimicking others is better.

**Comment by jewzaam** [comment]
@derek63 do you happen to have a reference to the JIRA about the EAP (or picketlink) login module issue we found that meant we couldn't support both SAML and client certs?

**Comment by jewzaam** [comment]
@alechenninger do you have time to investigate CORS for this to just have the client's browser pass the saml assertion directly?  Would mean no changes to how AuthN is done for the service.

**Comment by alechenninger** [comment]
Yep I will look into it. I think this would be a great way for future single page web apps that use Lightblue to behave in general.

**Comment by derek63** [comment]
@jewzaam It actually wasn't a bug in EAP that prevents Picketlink-based SAML and client certs from working together, but how they are both implemented.  The Picketlink SAML solution intercepts requests using a JBoss valve, and the cert based auth is a login module.  Valves always fire before login modules, so while we are able to enable SAML on the services, it causes cert based auth to stop working because all clients, including those with certs, are intercepted/redirected to the SAML login sequence.

**Comment by derek63** [comment]
We had previously discussed writing a custom proxy-like JBoss valve that would look for the presence of a certificate in the request and bypass the Picketlink SAML valve if it was found (or forward to the Picketlink SAML valve it was found).  Not sure of the level of effort there, but it may be less than writing an impersonation implementation

**Comment by derek63** [comment]
In order for the "some other authentication scheme" option to work without customization, we would need to pick something that can be defined in a login module, then we can (easily, with configuration) pick the order in which authentication schemes are tried.  Not sure if OAuth can be defined this way, but am pretty sure SAML cannot be (hence the use of the Picketlink valve).

**Comment by alechenninger** [comment]
@jewzaam @derek63 Did some research. Let me try to summarize:

> have the client's browser pass the saml assertion directly?

The issue with this is the assertion is kept server side; all that is communicated to the client are Java session cookies; one for IdP and one for each SP. Inside the sessions are the assertions. So AJAX calls have no access to this. This is the "Web SSO profile" of SAML2.0 and is cookie and browser redirect based. Other issue with Web profile is that the IdP is "discovered," so I'm not sure how that would work with a REST API. The AJAX call would have to follow redirects, and then eventually the response might be an HTML form if the user is not already logged in, which the AJAX call would have to be expecting and handle accordingly. There is a SAML2.0 profile that seems more suited to this use case, the [ECP profile](http://docs.oasis-open.org/security/saml/Post2.0/saml-ecp/v2.0/cs01/saml-ecp-v2.0-cs01.html#_Toc366664719), however Picketlink does not support it.

One option could be, if the application that is already authenticated with SAML can read the assertion programmatically (I have not yet found out how but I assume this must be possible...), to expose the assertion via a HTTP request for the authenticated user (so app is protected via SAML, then JS can make AJAX call to retrieve saml assertion once authenticated). Then this assertion could be used to talk to lightblue. There is a login module in picketlink that can work like this (you send the assertion using BASIC auth, and JAAS does the rest: https://github.com/picketlink/picketlink-bindings/blob/master/picketlink-jbas-common/src/main/java/org/picketlink/trust/jbossws/jaas/SAMLBearerTokenLoginModule.java). But this maybe seems a little hacky.

Still investigating other options.

**Comment by alechenninger** [comment]
After discussing with @jewzaam , it seems like the best path forward might be to eventually support OAuth and also eventually support integrating SAML with OAuth, as described in my previous comment. In the interim, the data management application will move toward making AJAX calls to a lightblue host directly, and, like lightblue itself, will only work with either cert based auth (meaning each user will need a cert), or unauth.

I think I will close this issue for now in that case? If anyone thinks that the "request as" feature would be useful regardless, please reopen.

Thanks all for the discussion!
