### ISSUE TITLE
crud/update operation does not support $pull

### ISSUE THREAD

**Issue by JankiGadhiya** [lightblue-platform/lightblue-rest#283]
crud/update operation does not support [**$pull**](https://docs.mongodb.com/manual/reference/operator/update/pull/). That is supported by mongodb for deleting any single-multiple array element.

**Comment by bserdar** [comment]
Use $foreach with $remove.

https://github.com/lightblue-platform/lightblue-docs-specs/blob/master/language_specification/update.md
