### ISSUE TITLE
Change the the metadata interface like the crud

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-rest#32]
On the https://github.com/lightblue-platform/lightblue-rest/issues/20 there was some changes to make all the rest methods to follow the pattern, I would like to know you guys agree to use the same pattern on the metadata interface (so it would be more intuitive to work with both data and metadata resources) (the class to change: https://github.com/lightblue-platform/lightblue-rest/blob/1ce33f966e79ed4f7a960c341cfb39742d6e48db/metadata/src/main/java/com/redhat/lightblue/rest/metadata/AbstractMetadataResource.java )

Also, I notice that the issue #20 deprecated a rest method ( see on https://github.com/lightblue-platform/lightblue-rest/commit/1ce33f966e79ed4f7a960c341cfb39742d6e48db ), would it be better if we remove it?

**Comment by jewzaam** [comment]
Closing.
