### ISSUE TITLE
Bundle lightblue-rdbms

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-rest#33]
It's not part of the crud rest war's right now.

**Comment by luan-cestari** [comment]
Done https://github.com/lightblue-platform/lightblue-rest/blob/e03e55d77eb8b2d0d8c20ae161ca8598ce4a80cd/crud/pom.xml#L64

**Comment by derek63** [comment]
RDBMS also needs to be included in metadata rest wars, so we can save RDBMS metadata.  Added this in https://github.com/lightblue-platform/lightblue-rest/pull/65
