### ISSUE TITLE
Expose some internal configurations as rest service

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-rest#37]
For example, the backend /database used, we should inform  the name and maybe the description so the user that will create the metadata don't have to guess the internal name of MongoDB driver. Some more details on http://dev.forum.lightblue.io/Lightblue-expose-the-configurations-using-rest-td219.html

**Comment by jewzaam** [comment]
I'll split into individual bits and keep publishing the version as part of Ana

**Comment by jewzaam** [comment]
version: https://github.com/lightblue-platform/lightblue-rest/issues/77
datastore: https://github.com/lightblue-platform/lightblue-rest/issues/78
commit / hash: https://github.com/lightblue-platform/lightblue-rest/issues/79

**Comment by jewzaam** [comment]
Closing this in favor of the three issues noted earlier.
