### ISSUE TITLE
Expose version as rest service

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-rest#77]
Add /version API to expose the current version.  Full URL's would be:

```
http://hostname:port/rest/metadata/version
http://hostname:port/rest/data/version
```

**Comment by jewzaam** [comment]
Updating initial comment to remove the bits about the applications.  There is a separate issue to add that in a footer: https://github.com/lightblue-platform/lightblue-applications/issues/23

**Comment by derek63** [comment]
It seems the Maven project info is not getting filtered into that version.jsp, as the version info is not being  returned when I hit /rest/data/version or /rest/metadata/version on my local instances or on our shared dev instance.  I went ahead an updated the Metadata Management app to pull in the info from .../version, so once this is resolved the version info should show up there.

**Comment by jewzaam** [comment]
It's following the same pattern as health.jsp which works (hit /rest/metadata/health for example).  Both services seem to be resolving /version as an API call.  After some reading around it looks like the servlet-mapping for the rest app having a url of '/*' will override all other servlet mappings.  What is confusing about this is /health works.

Options:
1. use a filter instead of mapping for the rest app
2. better constraint for the existing rest app mapping (multiple url-pattern entries that are more specific)
3. hijack health.jsp to have the version instead of just string "1"

I don't think we can do the second option as we need /* for things like GET entity versions API.  And for crud would have to remove the old insert API (PUT /<entity name>).
I don't want to spend time on 1.
Therefore 3 is the quickest to turn around.  I'll do that and be done.  I'll reach out to folks monitoring our lightblue deployments to see if they care what this call returns.

**Comment by derek63** [comment]
The version servlet/jsp does return a valid 200 response it is just empty.  I think the issue here is with the Maven filtering, so I think it would not work in health.jp either.  I have confirmed that the Maven metadata substitution works as expected if you just change version.jsp to version.html (same content)

**Comment by jewzaam** [comment]
My testing showed that everything /rest/{data,metadata}/* would return

```
[]
```

except for /rest/{data,metadata}/health which returned
```
1
```

Therefore I have put in PR #88 to hijack the health.jsp to have the version instead of a hard coded string.  I've confirmed locally that filtering is working on this file, filtering is enabled for all of webapp directory.  So unless travis doesn't allow this it should be good.

**Comment by derek63** [comment]
I stand corrected...the commit you just did does seem to work.  Will update the management app to look for it in /health instead of /version

**Comment by jewzaam** [comment]
Confirmed internal monitoring doesn't care what is returned, just that something is returned.
