### ISSUE TITLE
Regression & integration tests for rdbms 

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-rest#85]
This issues aims to hold many different suggestion about tests to be made for RDBMS module  seeks to uncover new bugs and check the functionalities using black box test model. Post comments with suggestion for tests. Also, each PR made for this issue will target an specific test (or small set of tests) to not make a huge PR with many different changes all together.

**Comment by dcrissman** [comment]
I am not sure if this is what you mean, but for LDAP I am standing in-memory instances of LDAP, Mongo, and Lightblue, then essentially running integration tests against it. You could essentially do the same using something like HSQLDB or Derby.

See: lightblue-ldap-integration-test module
 * ITCaseLdapCRUDControllerTest
 * AbstractCRUDController - Could potentially promote to core library for shared use.

**Comment by luan-cestari** [comment]
The nabble discussion http://dev.forum.lightblue.io/Regression-amp-integration-tests-for-rdbms-td344.html

**Comment by jewzaam** [comment]
Given our use of RDBMS today, we need to target find operations only right now.  Simple queries would be good to start with.  Migrations use just a time field to look for records.  The metadata used should be complex. Complex means it contains sub-documents and arrays.  Preferably the following scenarios:
* simple metadata, flat field structure
* metadata with single simple array (strings)
* metadata with single complex array (objects)
* metadata with single sub-document
* metadata with nested arrays (array of objects with arrays of objects)
* metadata with multiple layers of sub-documents (sub-doc with sub-doc)

And verify in the test that the response contains the proper structure, field names, and values.

**Comment by luan-cestari** [comment]
The changes needed can also involve the rdbms module. The PR https://github.com/lightblue-platform/lightblue-rdbms/pull/108 was made for handling this for this set of changes another PR will handle the changes for RDBMS

**Comment by luan-cestari** [comment]
PR with parcial changes needed https://github.com/lightblue-platform/lightblue-rest/pull/93
