### ISSUE TITLE
The /health servlet is successful even if services are not responding

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-rest#92]
Because it isn't checking the rest applications, it's possible for the servlet to be working but the service to be effectively offline.  Just had this happen in dev.  All node's /health endpoint reported just fine but any rest api calls were not successful.  We need something better!

**Comment by dcrissman** [comment]
I assume https://github.com/lightblue-platform/lightblue-healthcheck resolves this issue. I will go ahead and close this out, but let me know if you still have concerns.
