### ISSUE TITLE
Replace all Error.reset() using a Servlet Filter

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-rest#97]
I thought that we could replace the Error.reset() statements (like the following one https://github.com/lightblue-platform/lightblue-rest/blob/master/crud/src/main/java/com/redhat/lightblue/rest/crud/AbstractCrudResource.java#L98 ) using a single call inside a Java Servlet Filter class. Does anyone see a problem doing this ? I thought that would be helpful to avoid calling  Error.reset() indirectly by mistake when someone is refactoring a service to reuse another method.

**Comment by jewzaam** [comment]
Downside is scattering the logic about in various places.  Error.reset() is pretty important for getting the context correct.  We can leave this issue as a note that we'll have to deal with it if we ever have service API's call each other.
